name: build wiki

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  genrate-and-push-wiki:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version using SemVer's version range syntax
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone Terraria mod Journey's Trend
        run: |
          cd ..
          git clone https://${{ secrets.JT_REPO }}:x-oauth-basic@github.com/Qubus0/JourneyTrend.git
      - name: Generate Terraria mod wiki
        run: |
          cd generate_terraria_mod_wiki
          python3 generate_terraria_mod_wiki.py ../JourneyTrend
      - name: push to Journey's Trend wiki
        run: |
          cd ..
          git clone https://${{ secrets.JT_REPO }}:x-oauth-basic@github.com/Qubus0/JourneyTrend.wiki.git
          mv -v JourneyTrend-WikiGenerator/wiki/* JourneyTrend.wiki/
          cd JourneyTrend.wiki
          git add .
          git status